# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: version
    displayName: SonarQube Download version
    type: string
    default: 26.9.0.129388

# trigger:
#   branches:
#     include:
#       - feature/*
#       - release/*
#   tags:
#     include:
#       - '*'
# pr:
#   branches:
#     include:
#       - develop

resources:
  repositories:
    - repository: inventory
      type: github
      name: JamesJonesConsulting/AnsibleInventory
      endpoint: JamesJonesConsulting      
    - repository: vault
      type: github
      name: JamesJonesConsulting/AnsibleVault
      endpoint: JamesJonesConsulting
  containers:
    - container: podman-dind
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerNexusHosted
      options: --userns=keep-id --privileged --user root
pool: FedoraHosted
container: podman-dind
variables:
  - group: Connections
  - name: ARTIFACTORY_HOST
    value: nexus.jamesjonesconsulting.com

steps:
  - checkout: self 
    path: s/pipeline
  - checkout: inventory
    path: s/inventory
  - checkout: vault
    path: s/vault

  # - bash: |
  #     eval $(ssh-agent); ssh-add <(echo "${SSH_KEY}" | base64 -d);
  #     echo -n "${VAULT_KEY}" | base64 -d > $(Agent.TempDirectory)/.vault
  #   workingDirectory: $(Build.SourcesDirectory)/pipeline
  #   displayName: Connect to host and setup Azure DevOps agent with Podman
  #   env:
  #     SSH_KEY: $(default_ssh_key)
  #     VAULT_KEY: $(ansible_vault_key)
  - bash: |
      curl -L https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-${{ parameters.version }}.zip > sonarqube.zip
      unzip sonarqube.zip
      mv sonarqube-${{ parameters.version }} sonarqube
      mv sonarqube/conf/sonar.properties .
    workingDirectory: $(Build.SourcesDirectory)/pipeline
    displayName: Download and extra SonarQube zip
  - bash: |
      if [[ "$BUILD_SOURCEBRANCH" == refs/tags/* ]]; then
        tag="${BUILD_SOURCEBRANCH#refs/tags/}"

        echo "Tag: $tag"
        refName="${{ parameters.version }}.${tag}"

        echo "##vso[task.setvariable variable=gitRefType]tag"
        echo "##vso[task.setvariable variable=gitRefName]$tag"
      else
        branch="${BUILD_SOURCEBRANCH#refs/heads/}"

        # Replace "/" with "-"
        branch="${branch//\//-}"

        # Prepend the version and "~" to the branch name
        refName="${{ parameters.version }}~${branch}"

        echo "Branch: $refName"
        echo "##vso[task.setvariable variable=gitRefType]branch"
        echo "##vso[task.setvariable variable=gitRefName]$refName"
      fi
    displayName: Get version and normalized tag or branch name
    workingDirectory: $(Build.SourcesDirectory)/pipeline
  - bash: |
      echo "Reference type: $(gitRefType)"
      echo "Reference name: $(gitRefName)"
      fpm -s dir -t rpm -n sonarqube -v $(gitRefName) --iteration $(Build.BuildNumber) \
        --description "SonarQube Community Edition" \
        --url "https://github.com/JamesJonesConsulting/sonarqube_distro_packaging" \
        --license "LGPL3.0" --vendor "James Jones" \
        --config-files /opt/sonarqube/conf/sonar.properties \
        -p ./dist \
        ./sonarqube=/opt/sonarqube \
        ./sonar.properties=/opt/sonarqube/conf/sonar.properties

    displayName: Build the RPM package
    workingDirectory: $(Build.SourcesDirectory)/pipeline

