# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
  - name: version
    displayName: SonarQube Download version
    type: string
    default: 26.9.0.129388
  - name: target_group
    displayName: Target group for deployment
    type: string
    default: sonarqube
  - name: inventory
    displayName: Ansible inventory to use for deployment
    type: string
    default: home
    values:
      - home
trigger: none
# trigger:
#   branches:
#     include:
#       - feature/*
#       - release/*
#   tags:
#     include:
#       - '*'
# pr:
#   branches:
#     include:
#       - develop

resources:
  repositories:
    - repository: inventory
      type: github
      name: JamesJonesConsulting/AnsibleInventory
      endpoint: JamesJonesConsulting      
    - repository: vault
      type: github
      name: JamesJonesConsulting/AnsibleVault
      endpoint: JamesJonesConsulting
  containers:
    - container: podman-dind
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerNexusHosted
      options: --userns=keep-id --privileged --user root
pool: FedoraHosted
container: podman-dind
variables:
  - group: Connections
  - name: ARTIFACTORY_HOST
    value: nexus.jamesjonesconsulting.com

steps:
  - checkout: self 
    path: s/pipeline
  - checkout: inventory
    path: s/inventory
  - checkout: vault
    path: s/vault
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      eval $(ssh-agent); ssh-add <(echo "${SSH_KEY}" | base64 -d);
      echo -n "${VAULT_KEY}" | base64 -d > $(Agent.TempDirectory)/.vault
      ansible-playbook \
        -i $(Build.SourcesDirectory)/inventory/${{ parameters.inventory }}/hosts \
        --vault-password-file $(Agent.TempDirectory)/.vault \
        $(Build.SourcesDirectory)/pipeline/deploy/deploy.yml \
        -e "target_group=${{ parameters.target_group }}" \
        -b
    env:
      SSH_KEY: $(default_ssh_key)
      VAULT_KEY: $(ansible_vault_key)
    displayName: 'Setup SonarQube package on target hosts'
    workingDirectory: $(Build.SourcesDirectory)/pipeline
