# the server directive is Nginx's virtual host directive
server { 
 # port to listen on. Can also be set to an IP:PORT 
 listen 443 ssl;
 ssl_certificate {{ sonarqube_tls_cert }};
 ssl_certificate_key {{ sonarqube_tls_key }};
 ssl_trusted_certificate {{ sonarqube_tls_ca_chain }};
 location / {
   proxy_pass http://{{ sonarqube_host }}:{{ sonarqube_port }};
   proxy_set_header Host $host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Forwarded-Proto https;
 }
}