- name: Deploy SonarQube rpm package
  hosts: "{{ target_group }}"
  # connection: local
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Debug vars
      ansible.builtin.debug:
        msg: "{{ target_group }}"
