- name: Deploy SonarQube rpm package
  hosts: "{{ target_group }}"
  # connection: local
  vars_files:
    - ./vars/main.yml
  pre_tasks:
    - name: Ensure python3-libdnf5 is installed on the target hosts
      ansible.builtin.command:
        cmd: dnf install -y python3-libdnf5
  tasks:
    - name: Setup SonarQube Nexus repository
      ansible.builtin.copy:
        src: files/nexus-sonarqube.repo
        dest: /etc/yum.repos.d/nexus-sonarqube.repo
        owner: root
        group: root
        mode: '0644'
    - name: Clean all DNF caches
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true
    - name: Install SonarQube package
      ansible.builtin.dnf:
        name: sonarqube
        update_cache: true
        state: latest 
