- name: Deploy SonarQube rpm package
  hosts: "{{ target_group }}"
  # connection: local
  vars_files:
    - ./vars/main.yml
  pre_tasks:
    - name: Ensure python3-libdnf5 is installed on the target hosts
      ansible.builtin.command:
        cmd: dnf install -y python3-libdnf5
  tasks:
    - name: Setup SonarQube Nexus repository
      ansible.builtin.copy:
        src: files/nexus-sonarqube.repo
        dest: /etc/yum.repos.d/nexus-sonarqube.repo
        owner: root
        group: root
        mode: '0644'
    - name: Clean all DNF caches
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true
    - name: Install SonarQube package
      ansible.builtin.dnf:
        name: sonarqube
        update_cache: true
        state: latest
    - name: Update sonar.properties with the correct JDBC URL
      community.general.ini_file:
        path: /opt/sonarqube/conf/sonar.properties
        no_extra_spaces: true
        option: "{{ setting.option }}"
        value: "{{ setting.value }}"
      loop:
        - option: sonar.jdbc.username
          value: "{{ sonarqube_pg_user }}"
        - option: sonar.jdbc.password
          value: "{{ sonarqube_pg_pass }}"
        - option: sonar.jdbc.url
          value: "jdbc:postgresql://{{ sonarqube_db_host }}:{{ sonarqube_db_port }}/{{ sonarqube_db }}?currentSchema=public"
        - option: sonar.web.port
          value: "{{ sonarqube_port }}"
        - option: sonar.web.host
          value: "0.0.0.0"
        - option: sonar.web.https.port
          value: "{{ sonarqube_https_port }}"
        - option: sonar.web.ssl.port
          value: "{{ sonarqube_https_port }}"
        # - option: sonar.web.https.keyAlias
        #   value: "{{ sonarqube_https_alias }}"
        - option: sonar.web.https.keystoreFile
          value: "{{ sonarqube_keystore_file }}"
        - option: sonar.web.https.keyStoreType
          value: PKCS12
        - option: sonar.web.https.keyPass
          value: "{{ sonarqube_keystore_password }}"
      loop_control:
        loop_var: setting
    - name: Update sysctl values
      ansible.posix.sysctl:
        name: "{{ sysctl_setting.name }}"
        value: "{{ sysctl_setting.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/99-sonarqube.conf
      loop:
        - { name: net.ipv4.ip_unprivileged_port_start, value: 443 }
        - { name: vm.max_map_count, value: 524288 }
        - { name: fs.file-max, value: 131072 }
        - { name: kernel.pid_max, value: 65536 }
      loop_control:
        loop_var: sysctl_setting
    - name: Ensure the SonarQube Keystore directory exists
      ansible.builtin.file:
        path: "{{ sonarqube_keystore_file | dirname }}"
        state: directory
        owner: sonarqube
        group: sonarqube
        mode: "0750"
    - name: Ensure any exiting keystore file is removed before creating a new one
      ansible.builtin.file:
        path: "{{ sonarqube_keystore_file }}"
        state: absent
    - name: Create PKCS#12 keystore
      ansible.builtin.command:
        argv:
          - openssl
          - pkcs12
          - -export
          - -out
          - "{{ sonarqube_keystore_file }}"
          - -inkey
          - "{{ sonarqube_tls_key }}"
          - -in
          - "{{ sonarqube_tls_cert }}"
          - -certfile
          - "{{ sonarqube_tls_ca_chain }}"
          - -name
          - "{{ sonarqube_https_alias }}"
          - -passout
          - "pass:{{ sonarqube_keystore_password }}"
      args:
        creates: "{{ sonarqube_keystore_file }}"
      no_log: true
    - name: Ensure the SonarQube keystore is owned by the SonarQube service account
      ansible.builtin.file:
        path: "{{ sonarqube_keystore_file }}"
        owner: sonarqube
        group: sonarqube
        mode: "0640"
    - name: Enable and start SonarQube service
      ansible.builtin.systemd:
        name: sonarqube
        enabled: true
        state: restarted
        daemon_reload: true
    - name: Add SonarQube Nginx configuration
      ansible.builtin.copy:
        src: templates/sonarqube-nginx.conf
        dest: /etc/nginx/conf.d/sonarqube.conf
        owner: root
        group: root
        mode: '0644'
